'use strict';
const width = 20;
const height = 15;
const area = width * height;
console.log('What is the area?', area);
console.log('Type:', typeof area);
const bill = 28;
const payment = 30;
const change = payment - bill;
console.log('What is the change?', change);
console.log('Type:', typeof change);
const quizzes = 89;
const midterm = 83;
const final = 93;
const grade = quizzes + midterm + final / 3;
console.log('What is the grade?', grade);
console.log('Type:', typeof grade);
const firstName = 'Johan';
const lastName = 'Sangalang';
const fullName = firstName + ' ' + lastName;
console.log('What is fullname?', fullName);
console.log('Type:', typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log('Is acidic?', isAcidic);
console.log('Type:', typeof isAcidic);
const headCount = 222;
const isSparta = headCount === 300;
console.log('Is Sparta?', isSparta);
console.log('Type:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('What is the motto?', motto);
console.log('Type:', typeof motto);
