'use strict';
let width = 20;
let height = 15;
let area = width * height;
console.log('What is the area?', area);
console.log('Type:', typeof area);
let bill = 28;
let payment = 30;
let change = payment - bill;
console.log('What is the change?', change);
console.log('Type:', typeof change);
let quizzes = 89;
let midterm = 83;
let final = 93;
let grade = quizzes + midterm + final / 3;
console.log('What is the grade?', grade);
console.log('Type:', typeof grade);
let firstName = 'Johan';
let lastName = 'Sangalang';
let fullName = firstName + ' ' + lastName;
console.log('What is fullname?', fullName);
console.log('Type:', typeof fullName);
let pH = 9;
let isAcidic = pH < 7;
console.log('Is acidic?', isAcidic);
console.log('Type:', typeof isAcidic);
let headCount = 222;
let isSparta = headCount === 300;
console.log('Is Sparta?', isSparta);
console.log('Type:', typeof isSparta);
let motto = fullName + ' is the GOAT';
console.log('What is the motto?', motto);
console.log('Type:', typeof motto);
